
dataDir : 'pseudotime/data/monocle/metaneighbor/'

terms_file : '/home/bharris/pseudotime/scripts/mn_pipeline/test_terms.csv'

dataset_filename : '/home/bharris/pseudotime/data/monocle/erythroid_and_monocyte_lineage_adata.h5ad'
dataset_name : 'erythroid_and_monocyte'
mkl_threads : 8

n_bins : 16

prepare_terms :
  terms_dir : '/home/bharris/pseudotime/data/monocle/metaneighbor/tabula_muris_genelists/'
  terms_design : '/home/bharris/pseudotime/data/monocle/metaneighbor/tabula_muris_markers_design.csv'
  min_size : 10
  max_size : 100
  

metaneighbor :
  join_bin : 'lineage'
  rank_by : 'monocle_ps'
  study_col : 'study_id'
  pseudotime_col: 'monocle_ps'
  max_genes : 100
  fast_version : True
continuity :
  threshold : .7